name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js v12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Test
      run: |
        npm install
        npm run test